/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: device_info.proto */

#ifndef PROTOBUF_C_device_5finfo_2eproto__INCLUDED
#define PROTOBUF_C_device_5finfo_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _DeviceInfo DeviceInfo;


/* --- enums --- */


/* --- messages --- */

struct  _DeviceInfo
{
  ProtobufCMessage base;
  char *device_name;
  int32_t firmware_version;
  char *device_type;
  int32_t voltage_rating;
  protobuf_c_boolean supports_wifi;
};
#define DEVICE_INFO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&device_info__descriptor) \
    , NULL, 0, NULL, 0, 0 }


/* DeviceInfo methods */
void   device_info__init
                     (DeviceInfo         *message);
size_t device_info__get_packed_size
                     (const DeviceInfo   *message);
size_t device_info__pack
                     (const DeviceInfo   *message,
                      uint8_t             *out);
size_t device_info__pack_to_buffer
                     (const DeviceInfo   *message,
                      ProtobufCBuffer     *buffer);
DeviceInfo *
       device_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   device_info__free_unpacked
                     (DeviceInfo *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*DeviceInfo_Closure)
                 (const DeviceInfo *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor device_info__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_device_5finfo_2eproto__INCLUDED */
