/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: device_info.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "device_info.pb-c.h"
void   device_info__init
                     (DeviceInfo         *message)
{
  static const DeviceInfo init_value = DEVICE_INFO__INIT;
  *message = init_value;
}
size_t device_info__get_packed_size
                     (const DeviceInfo *message)
{
  assert(message->base.descriptor == &device_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t device_info__pack
                     (const DeviceInfo *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &device_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t device_info__pack_to_buffer
                     (const DeviceInfo *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &device_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DeviceInfo *
       device_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DeviceInfo *)
     protobuf_c_message_unpack (&device_info__descriptor,
                                allocator, len, data);
}
void   device_info__free_unpacked
                     (DeviceInfo *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &device_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor device_info__field_descriptors[5] =
{
  {
    "device_name",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DeviceInfo, device_name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "firmware_version",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(DeviceInfo, firmware_version),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "device_type",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DeviceInfo, device_type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "voltage_rating",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(DeviceInfo, voltage_rating),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "supports_wifi",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(DeviceInfo, supports_wifi),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned device_info__field_indices_by_name[] = {
  0,   /* field[0] = device_name */
  2,   /* field[2] = device_type */
  1,   /* field[1] = firmware_version */
  4,   /* field[4] = supports_wifi */
  3,   /* field[3] = voltage_rating */
};
static const ProtobufCIntRange device_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor device_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DeviceInfo",
  "DeviceInfo",
  "DeviceInfo",
  "",
  sizeof(DeviceInfo),
  5,
  device_info__field_descriptors,
  device_info__field_indices_by_name,
  1,  device_info__number_ranges,
  (ProtobufCMessageInit) device_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
