# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/device_feature.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aproto/device_feature.proto\"\x9a\x01\n\x0e\x44\x65vice_Feature\x12\x18\n\x0b\x64\x65vice_type\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x1b\n\x0evoltage_rating\x18\x02 \x01(\x05H\x01\x88\x01\x01\x12\x1b\n\x0e\x63urrent_rating\x18\x03 \x01(\x05H\x02\x88\x01\x01\x42\x0e\n\x0c_device_typeB\x11\n\x0f_voltage_ratingB\x11\n\x0f_current_ratingb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.device_feature_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DEVICE_FEATURE._serialized_start=31
  _DEVICE_FEATURE._serialized_end=185
# @@protoc_insertion_point(module_scope)
