/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: device_feature.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "device_feature.pb-c.h"
void   device__feature__init
                     (DeviceFeature         *message)
{
  static const DeviceFeature init_value = DEVICE__FEATURE__INIT;
  *message = init_value;
}
size_t device__feature__get_packed_size
                     (const DeviceFeature *message)
{
  assert(message->base.descriptor == &device__feature__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t device__feature__pack
                     (const DeviceFeature *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &device__feature__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t device__feature__pack_to_buffer
                     (const DeviceFeature *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &device__feature__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DeviceFeature *
       device__feature__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DeviceFeature *)
     protobuf_c_message_unpack (&device__feature__descriptor,
                                allocator, len, data);
}
void   device__feature__free_unpacked
                     (DeviceFeature *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &device__feature__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor device__feature__field_descriptors[3] =
{
  {
    "device_type",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DeviceFeature, device_type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "voltage_rating",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(DeviceFeature, has_voltage_rating),
    offsetof(DeviceFeature, voltage_rating),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "current_rating",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(DeviceFeature, has_current_rating),
    offsetof(DeviceFeature, current_rating),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned device__feature__field_indices_by_name[] = {
  2,   /* field[2] = current_rating */
  0,   /* field[0] = device_type */
  1,   /* field[1] = voltage_rating */
};
static const ProtobufCIntRange device__feature__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor device__feature__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Device_Feature",
  "DeviceFeature",
  "DeviceFeature",
  "",
  sizeof(DeviceFeature),
  3,
  device__feature__field_descriptors,
  device__feature__field_indices_by_name,
  1,  device__feature__number_ranges,
  (ProtobufCMessageInit) device__feature__init,
  NULL,NULL,NULL    /* reserved[123] */
};
